services:
  api:
    build:
      context: .
      dockerfile: src/ApiSecurity.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=postgres;Port=5432;Database=apisecurity;Username=postgres;Password=postgres
      - Jwt__SigningKey=dev-signing-key-replace-in-production-minimum-32!!
    depends_on:
      postgres:
        condition: service_healthy
      seq:
        condition: service_started
    networks:
      - api-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: apisecurity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - api-net

  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "5341:80"
    networks:
      - api-net

volumes:
  pg_data:

networks:
  api-net:
